# Generated by Django 4.0.4 on 2022-06-20 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_message_room_alter_message_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
