# Generated by Django 4.0.4 on 2022-06-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_delete_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
