# Generated by Django 4.0.4 on 2022-06-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='img',
            field=models.ImageField(default=None, null=True, upload_to='images'),
        ),
    ]
